apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: e-marketplace-ingress
  namespace: e-marketplace
  #annotations:
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    # If you encounter a redirect loop or are getting a 307 response code
    # then you need to force the nginx ingress to connect to the backend using HTTPS.
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: "nginx"
  rules:
  - host: e-marketplace.devops-warrior.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: e-marketplace
            port:
              name: http