apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-marketplace
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: e-marketplace
  template:
    metadata:
      labels:
        app: e-marketplace
    spec:
      containers:
      - image: feriva22/e-marketplace:latest
        name: e-marketplace
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: e-marketplace-configmap
        - secretRef:
            name: e-marketplace-secret
