name: "Deploy to Argo CD"
on:
  workflow_run:
    workflows: ["CI Testing"]
    branches: [main]
    types: 
      - completed
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install and configure kubectl
      uses: azure/setup-kubectl@v1

    - name: Install Argo CD CLI
      run: |
        curl -LO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x argocd-linux-amd64
        sudo mv argocd-linux-amd64 /usr/local/bin/argocd

    - name: Login to Argo CD
      run: argocd login --insecure --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web ${{ secrets.ARGOCD_API_SERVER }}

    - name: Sync Application
      run: argocd app sync e-marketplace
    
